# this cop support only rails 5
Rails/HttpPositionalArguments:
   Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

RSpec/MultipleExpectations:
   Enabled: false

RSpec/NestedGroups:
   Enabled: false

Rails/TimeZone:
   Enabled: false

Rails/ApplicationRecord:
   Enabled: false