# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73156a8a57e85881349114e9348fcd6575e5270cfd8670fe22503c927818b6c6d113ba29a9ec081252e96c13faf68b9330047e57aa59405bbdf4230772a80c1b

test:
  secret_key_base: 1c2e23a842faec769c379a3f5718ca69d0b17e868fdf10eb18c7becfa781970c4083d1bf77bc465eeff93ba814fde503354aa8f0bf8bd3cba3ef9f6d7ef28b1b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
